# Generated by Django 4.2 on 2025-06-25 11:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_hostel_remove_order_room_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='08031234567', max_length=128, region=None),
        ),
    ]
