# Generated by Django 4.2 on 2025-06-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
