# Generated by Django 4.2 on 2025-06-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
