# Generated by Django 4.2 on 2026-05-11 14:55

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_product_image_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Enter a valid price greater than 0.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=cloudinary.models.CloudinaryField(default='image_url', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
