# Generated by Django 4.2 on 2026-06-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_price_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='fulfilled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('waiting approval', 'waiting approval'), ('active', 'active'), ('deleted', 'deleted')], db_index=True, default='active', max_length=50),
        ),
    ]
