# Generated by Django 4.2 on 2026-10-06 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


def backfill_paid_at(apps, schema_editor):
    """Existing paid orders have no paid_at; their creation time is the best
    available approximation and keeps order lists sorted sensibly."""
    Order = apps.get_model("store", "Order")
    for order in Order.objects.filter(is_paid=True, paid_at__isnull=True).only("pk", "created_at"):
        Order.objects.filter(pk=order.pk).update(paid_at=order.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_add_indexes_fix_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(choices=[('admin', 'Admin Block'), ('faculty', 'Faculty Building'), ('tetfund', 'TETFund Building'), ('hall_1', 'Hall 1'), ('hall_2', 'Hall 2'), ('hall_3', 'Hall 3'), ('hall_4', 'Hall 4'), ('hall_5', 'Hall 5'), ('hall_6', 'Hall 6'), ('hall_7', 'Hall 7'), ('hall_8', 'Hall 8')], default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='store.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, message='Rating must be between 1 and 5.'), django.core.validators.MaxValueValidator(5, message='Rating must be between 1 and 5.')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(backfill_paid_at, migrations.RunPython.noop),
    ]
