# Generated by Django 4.2 on 2026-10-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_paid_at_order_service_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('refund_order', 'Can refund paid orders'), ('recheck_payment', 'Can re-check payments with Paystack')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'permissions': [('moderate_product', 'Can hide or restore listings'), ('feature_product', 'Can feature or unfeature listings')]},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('moderate_review', 'Can hide or restore reviews')]},
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('', 'Not refunded'), ('pending', 'Refund pending'), ('processed', 'Refunded'), ('failed', 'Refund failed')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('waiting approval', 'waiting approval'), ('active', 'active'), ('deleted', 'deleted'), ('hidden', 'hidden by staff')], db_index=True, default='active', max_length=50),
        ),
    ]
