# Generated by Django 4.2 on 2025-02-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logo'),
        ),
    ]
