# Generated by Django 4.2 on 2025-06-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_vendorprofile_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='account_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
