# Generated by Django 4.2 on 2025-06-29 00:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_remove_vendorprofile_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('external', 'External')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(help_text='Monthly price in NGN')),
                ('max_products', models.IntegerField(blank=True, help_text='Max number of products allowed', null=True)),
                ('paystack_plan_code', models.CharField(blank=True, help_text='Paystack plan code if integrated', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='bank_code',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pending_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_start',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 29, 0, 38, 10, 699727, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('grace', 'Grace Period'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.vendorplan'),
        ),
    ]
