# Generated by Django 4.2 on 2025-10-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_vendorprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hostel',
            field=models.CharField(blank=True, choices=[('hall_1', 'Hall 1'), ('hall_2', 'Hall 2'), ('hall_3', 'Hall 3'), ('hall_4', 'Hall 4'), ('hall_5', 'Hall 5'), ('hall_6', 'Hall 6'), ('hall_7', 'Hall 7'), ('hall_8', 'Hall 8')], help_text='Select your hostel', max_length=20, null=True),
        ),
    ]
