# Generated by Django 4.2 on 2025-10-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='failed_payment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pause_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial Period'), ('active', 'Active'), ('grace', 'Grace Period'), ('paused', 'Paused'), ('defaulted', 'Payment Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=50),
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('subscription_created', 'Subscription Created'), ('plan_upgraded', 'Plan Upgraded'), ('plan_downgraded', 'Plan Downgraded'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_paused', 'Subscription Paused'), ('subscription_resumed', 'Subscription Resumed'), ('subscription_cancelled', 'Subscription Cancelled'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('grace_period_started', 'Grace Period Started'), ('subscription_expired', 'Subscription Expired')], max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('paystack_response', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_subscriptions', to='userprofile.vendorplan')),
                ('previous_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_subscriptions', to='userprofile.vendorplan')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='userprofile.vendorprofile')),
            ],
            options={
                'verbose_name_plural': 'Subscription History',
                'ordering': ['-created_at'],
            },
        ),
    ]
