# Generated by Django 4.2 on 2025-11-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='verification_type',
            field=models.CharField(choices=[('signup', 'Signup Verification'), ('password_reset', 'Password Reset')], default='signup', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='emailverification',
            unique_together={('email', 'verification_type', 'is_used')},
        ),
    ]
