# Generated by Django 4.2 on 2025-11-01 09:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_emailverification_verification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload your profile picture', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='store_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
