# Generated by Django 4.2 on 2025-11-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_alter_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
