# Generated by Django 4.2 on 2026-02-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_add_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorplan',
            name='features',
            field=models.TextField(blank=True, help_text='List of plan features (one per line)'),
        ),
        migrations.AlterField(
            model_name='vendorplan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('premium', 'Premium'), ('external', 'External')], max_length=50, unique=True),
        ),
    ]
