# Generated by Django 4.2 on 2026-02-26 00:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_add_features_and_pro_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='NG', unique=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='NG', unique=True),
        ),
    ]
