# Generated by Django 4.2 on 2026-10-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_emailverification_attempts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('suspend_user', 'Can suspend or restore user accounts')]},
        ),
        migrations.AlterModelOptions(
            name='vendorprofile',
            options={'permissions': [('suspend_vendor', 'Can suspend or restore vendor stores')]},
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_suspended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
