# Generated by Django 4.2 on 2026-10-06 19:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import operations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0018_alter_order_options_alter_product_options_and_more'),
        ('userprofile', '0018_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Permanent identifier, e.g. hall_2.', unique=True)),
                ('label', models.CharField(help_text='What buyers see, e.g. Hall 2.', max_length=80)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive locations can't be chosen at checkout.")),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=operations.models._ticket_reference, editable=False, max_length=12, unique=True)),
                ('kind', models.CharField(choices=[('order_problem', 'Problem with an order'), ('payment', 'Payment problem'), ('report_vendor', 'Report a vendor'), ('report_listing', 'Report a listing'), ('report_review', 'Report a review'), ('account', 'Account help'), ('other', 'Something else')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('waiting_on_user', 'Waiting on user'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10)),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='store.product')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='store.review')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='userprofile.vendorprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes are only visible to staff.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='operations.supportticket')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_days', models.PositiveSmallIntegerField(default=30, help_text='Length of the free trial new vendors get. Applies to new vendors only.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)])),
                ('grace_days', models.PositiveSmallIntegerField(default=7, help_text='Days a lapsed paid vendor keeps selling before their listings are hidden.', validators=[django.core.validators.MaxValueValidator(30)])),
                ('max_quantity_per_item', models.PositiveSmallIntegerField(default=50, help_text='Most units of one product a buyer can have in their cart.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('accepting_orders', models.BooleanField(default=True, help_text='Turn off to pause checkout everywhere (e.g. during an incident). Browsing still works.')),
                ('orders_paused_message', models.CharField(blank=True, default='Checkout is paused for a short while. Please try again soon.', help_text='Shown to buyers while checkout is paused.', max_length=200)),
                ('vendor_signups_open', models.BooleanField(default=True, help_text='Turn off to stop new vendors from registering.')),
                ('support_email', models.EmailField(default='support@vendorxprt.com', max_length=254)),
                ('announcement', models.CharField(blank=True, help_text='Banner shown at the top of the marketplace. Leave empty for none.', max_length=240)),
                ('announcement_level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning')], default='info', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_label', models.CharField(help_text='Actor email at the time of the action.', max_length=254)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('target_label', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Before/after values.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
